<?php
    $motsVides = array(
         " à " ,  " afin " ,  " ai " ,  " ainsi " ,  " après " ,  " au " ,  " aucun " ,  " aucune " ,  " aussi " ,  " autour " ,
         " avait " ,  " avant " ,  " avec " ,  " avoir " ,  " c’ " ,  " car " ,  " ce " ,  " cela " ,  " ces " ,  " cette " ,
         " ceux " ,  " ci " ,  " comme " ,  " comment " ,  " d " ,  " dans " ,  " de " ,  " dedans " ,  " dehors " ,  " depuis " ,
         " des " ,  " deux " ,  " devrait " ,  " doit " ,  " donc " ,  " dont " ,  " du " ,  " elle " ,  " elles " ,  " en " ,
         " encore " ,  " entre " ,  " est " ,  " et " ,  " eu " ,  " eux " ,  " ici " ,  " il " ,  " ils " ,  " je " ,
         " juste " ,  " la " ,  " le " ,  " les " ,  " leur " ,  " là " ,  " ma " ,  " maintenant " ,  " mais " ,  " me " ,
         " même " ,  " mes " ,  " moi " ,  " mon " ,  " ne " ,  " ni " ,  " non " ,  " nos " ,  " notre " ,  " nous " ,
         " on " ,  " ou " ,  " où " ,  " par " ,  " parce " ,  " pas " ,  " peut " ,  " peu " ,  " pièce " ,  " plupart " ,
         " pour " ,  " pourquoi " ,  " quand " ,  " que " ,  " quel " ,  " quelle " ,  " quelles " ,  " quels " ,  " qui " ,  " sa " ,
         " sans " ,  " se " ,  " serait " ,  " si " ,  " soi " ,  " soit " ,  " son " ,  " sont " ,  " sous " ,  " sujet " ,
         " sur " ,  " ta " ,  " tandis " ,  " tellement " ,  " tels " ,  " tes " ,  " ton " ,  " tous " ,  " tout " ,  " trop " ,
         " très " ,  " tu " ,  " un " ,  " une " ,  " valeur " ,  " voici " ,  " voie " ,  " voient " ,  " vont " ,  " votre " ,
         " vous " ,  " vu " , " l’", " d’", " travers "," ses ", ' qu’', " a ",
    ' vers ',
    ' aux ',
    ' avec ',
    ' ce ',
    ' ces ',
    ' dans ',
    ' de ',
    ' des ',
    ' du ',
    ' elle ',
    ' en ',
    ' et ',
    ' eux ',
    ' il ',
    ' je ',
    ' la ',
    ' le ',
    ' leur ',
    ' lui ',
    ' ma ',
    ' mais ',
    ' me ',
    ' même ',
    ' mes ',
    ' moi ',
    ' mon ',
    ' ne ',
    ' nos ',
    ' notre ',
    ' nous ',
    ' on ',
    ' ou ',
    ' par ',
    ' pas ',
    ' pour ',
    ' qu ',
    ' que ',
    ' qui ',
    ' sa ',
    ' se ',
    ' ses ',
    ' son ',
    ' sur ',
    ' ta ',
    ' te ',
    ' tes ',
    ' toi ',
    ' ton ',
    ' tu ',
    ' un ',
    ' une ',
    ' vos ',
    ' votre ',
    ' vous ',
    ' c ',
    ' d ',
    ' j ',
    ' l ',
    ' à ',
    ' m ',
    ' n ',
    ' s ',
    ' t ',
    ' y ',
    ' été ',
    ' étée ',
    ' étées ',
    ' étés ',
    ' étant ',
    ' étante ',
    ' étants ',
    ' étantes ',
    ' suis ',
    ' es ',
    ' est ',
    ' sommes ',
    ' êtes ',
    ' sont ',
    ' serai ',
    ' seras ',
    ' sera ',
    ' serons ',
    ' serez ',
    ' seront ',
    ' serais ',
    ' serait ',
    ' serions ',
    ' seriez ',
    ' seraient ',
    ' étais ',
    ' était ',
    ' étions ',
    ' étiez ',
    ' étaient ',
    ' fus ',
    ' fut ',
    ' fûmes ',
    ' fûtes ',
    ' furent ',
    ' sois ',
    ' soit ',
    ' soyons ',
    ' soyez ',
    ' soient ',
    ' fusse ',
    ' fusses ',
    ' fût ',
    ' fussions ',
    ' fussiez ',
    ' fussent ',
    ' ayant ',
    ' ayante ',
    ' ayantes ',
    ' ayants ',
    ' eu ',
    ' eue ',
    ' eues ',
    ' eus ',
    ' ai ',
    ' as ',
    ' avons ',
    ' avez ',
    ' ont ',
    ' aurai ',
    ' auras ',
    ' aura ',
    ' aurons ',
    ' aurez ',
    ' auront ',
    ' aurais ',
    ' aurait ',
    ' aurions ',
    ' auriez ',
    ' auraient ',
    ' avais ',
    ' avait ',
    ' avions ',
    ' aviez ',
    ' avaient ',
    ' eut ',
    ' eûmes ',
    ' eûtes ',
    ' eurent ',
    ' aie ',
    ' aies ',
    ' ait ',
    ' ayons ',
    ' ayez ',
    ' aient ',
    ' eusse ',
    ' eusses ',
    ' eût ',
    ' eussions ',
    ' eussiez ',
    'jusqu’à'
    );
?>